name: Server test

on:
  push:
  pull_request:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: server
    env:
      SWOOLE_DOCKER_VERSION: 5.0-php8.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          docker run --name swoole --volume=${GITHUB_WORKSPACE}:/app:rw --workdir=/app -d phpswoole/swoole:$SWOOLE_DOCKER_VERSION
          docker exec swoole php -v
          docker exec swoole php --ri swoole
          docker exec swoole composer -V
          docker exec swoole composer update --no-interaction --prefer-dist --no-progress

      - name: Test
        run: docker exec swoole composer check-format

  phpstan:
    runs-on: ubuntu-20.04
    env:
      SWOOLE_DOCKER_VERSION: 5.0-php8.1
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          docker run --name swoole --volume=${GITHUB_WORKSPACE}:/app:rw --workdir=/app -d phpswoole/swoole:$SWOOLE_DOCKER_VERSION
          docker exec swoole php -v
          docker exec swoole php --ri swoole
          docker exec swoole composer -V
          docker exec swoole composer update --no-interaction --prefer-dist --no-progress

      - name: Test
        run: docker exec swoole composer phpstan
