name: Web test

on:
  push:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm lint

  vue-tsc:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Typecheck
        run: pnpm type-check
